### Makefile -- Miscellaneous modules

# Author: Michael Grünewald
# Date: Sat Jul  7 18:09:47 CEST 2007

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

SHARE=			elisp.lib.mk
SHARE+=			generic.files.mk
SHARE+=			generic.subdir.mk
SHARE+=			generic.project.mk
SHARE+=			generic.test.mk

.include "generic.files.mk"

### End of file `Makefile'
