### Makefile -- Collection de makefiles `misc'

# Author: Michaël Grünewald
# Date: Sam  7 jul 2007 18:09:47 CEST
# Lang: fr_FR.ISO8859-1

# $Id$


FILES+= misc.script.mk
FILES+=	misc.elisp.mk
FILES+=	misc.dotfile.mk

.include "project.mk"

### End of file `Makefile'
