### Makefile -- Miscellaneous modules

# Author: Michael Grünewald
# Date: Sat Jul  7 18:09:47 CEST 2007

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

SHARE=			elisp.lib.mk
SHARE+=			generic.files.mk
SHARE+=			generic.subdir.mk
SHARE+=			generic.project.mk
SHARE+=			generic.test.mk

.include "generic.files.mk"

### End of file `Makefile'
