.TH MP2EPS 1 "Oct 27, 2014"
.SH NAME
mp2eps \- Convert METAPOST to encapsulated PostScript
.SH SYNOPSIS
.B mp2eps
.RI file1\ ...
.SH DESCRIPTION
.sp 2
.B mp2eps
converts METAPOST output to encapsulated PostScript. It uses TeX and epsf.tex.
.SH SEE ALSO
.BR tex (1).
.br
.SH AUTHOR
This manual page was written by Michael Grünewald
<michpili@gmail.com>.
