.TH MP2PNG 1 "Oct 27, 2014"
.SH NAME
mp2png \- Convert METAPOST to PNG
.SH SYNOPSIS
.B mp2png
.RI [\fI-r\ resolution\fR]\ file1\ ...
.SH DESCRIPTION
.sp 2
.B mp2png
converts METAPOST output to PNG.
.SH OPTIONS
.TP
\fB-r resolution\fR
Use the given resolution for rendering PNG. The implcit value is 1200
dpi.
.SH SEE ALSO
.BR gm (1).
.br
.SH AUTHOR
This manual page was written by Michael Grünewald
<michpili@gmail.com>.
