### Makefile -- Preparation of the golden_ratio manual

# Author: Michael Grünewald
# Date: Tue Oct 15 21:37:11 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

ODOC_TITLE=		Golden Ratio

.include "ocaml.manual.mk"

### End of file `Makefile'
