.\" librational.3 -- Compute on rational numbers
.\"
.\" Author: Michael Grünewald
.\" Date: Fri Nov  7 23:09:33 CET 2014
.\"
.\" BSD Owl Scripts (https://github.com/michipili/bsdowl)
.\" This file is part of BSD Owl Scripts
.\"
.\" Copyright © 2002–2016 Michael Grünewald
.\"
.\" This file must be used under the terms of the CeCILL-B.
.\" This source file is licensed as described in the file COPYING, which
.\" you should have received as part of this distribution. The terms
.\" are also available at
.\" http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt
.\"
.Dd November 7, 2014
.Dt LIBRATIONAL 3
.Os
.Sh NAME
.Nm librational
.Nd Compute on rational numbers
.Sh LIBRARY
.Lb librational
.Sh SYNOPSIS
.In rational.h
.Sh DESCRIPTION
The
.Lb librational
provides functions that allow an application to compute and print
rational numbers.
.Sh SEE ALSO
The
.Em GNU multiple precision arithmetic library
is a starting point if you actually need arithmetic on rational
numbers.
.Sh HISTORY
The
.Nm
library appeared as a demonstration library for bsdowl.
.Sh AUTHORS
.An -nosplit
This heat generating
.Nm
library was written by
.An Michael Gr\(:unewald Aq michipili@gmail.com .
