### Makefile -- A very simple library

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

LIBRARY=		rational

APIVERSION=		1
LIBVERSION=		${APIVERSION}.0.0

SRCS=			rational.h
SRCS+=			rational_trace.h
SRCS+=			rational_trace.c
SRCS+=			rational_operation.c
SRCS+=			rational_print.c

MAN=			librational.3


.include "langc.lib.mk"

### End of `Makefile'
