### Makefile -- A very simple library

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		rational

APIVERSION=		1
LIBVERSION=		${APIVERSION}.0.0

SRCS=			rational.h
SRCS+=			rational_trace.h
SRCS+=			rational_trace.c
SRCS+=			rational_operation.c
SRCS+=			rational_print.c

MAN=			librational.3


.include "langc.lib.mk"

### End of `Makefile'
