### Makefile -- Scripts that converts DATA from one format to another

# Author: Michaël Grünewald
# Date: Ven  9 mai 2008 14:47:47 CEST
# Lang: fr_FR.ISO8859-15

# $Id$

SCRIPT+= mp2eps.sh
SCRIPT+= mp2png.sh
SCRIPT+= mp2pdf.sh

.include "script.mk"

### End of file `Makefile'
