### Makefile -- Support scripts for BSD Owl Scripts

# Author: Michael Grünewald
# Date: Fri Mai  9 14:47:47 CEST 2008

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

PROGRAM=		mp2png.sh

.include "shell.prog.mk"

### End of file `Makefile'
