### Makefile -- Support scripts for BSD Owl Scripts

# Author: Michael Grünewald
# Date: Ven Mai  9 2008 14:47:47 CEST

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

PROGRAM=		mp2eps.sh
PROGRAM+=		mp2png.sh

.include "shell.prog.mk"

### End of file `Makefile'
