### Makefile -- How does it feel, when you have no home?

# Author: Michael Grünewald
# Date: Thu Oct  3 22:42:23 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

PROGRAM=	rolling_stone
EXTERNAL=	ocaml.findlib:unix

.include "ocaml.prog.mk"

### End of file `Makefile'
