### Makefile -- Test tex.texdoc.mk and co.

DOCS = toto.tex

FIGS.toto = illustrations.mp

TEX = pdftex
FORMAT.dvi = brid_dvips
FORMAT.pdf = brid_pdf

SRCS = extra.tex

TEXINPUTS.toto = .. :

.include "tex.doc.mk"

### End of file `Makefile'
