### Makefile -- Collection pour les scripts du ROX-Filer

# Author: Michaël Le Barbier Grünewald
# Date: Sam  7 jul 2007 18:12:40 CEST
# Lang: fr_FR.ISO8859-1

# $Id$


FILES+=	rox.init.mk
FILES+= rox.mime.mk
FILES+= rox.sendto.mk
FILES+= rox.template.mk

.include "project.mk"

### End of file `Makefile'
