### Makefile -- Test portability issues for BSD Make

# Author: Michael Grünewald
# Date: Tue Dec  2 22:31:53 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

TEST=			AssertMakeOS
TEST+=			AssertOneWord

TEST_SEQUENCE?=		all

.include "bsdowl.test.mk"

### End of file `Makefile'
