### Makefile -- Support for TeX and METAPOST

# Author: Michael Grünewald
# Date: Sat Jul  7 18:12:07 CEST 2007

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

SHARE=			texmf.init.mk
SHARE+=			texmf.uses.mk
SHARE+=			texmf.module.mk
SHARE+=			texmf.external.mk
SHARE+=			texmf.depend.mk
SHARE+=			texmf.clean.mk
SHARE+=			texmf.build.mk
SHARE+=			texmf.mpost.mk
SHARE+=			texmf.draft.mk
SHARE+=			texmf.bibtex.mk
SHARE+=			texmf.index.mk

SHARE+=			tex.doc.mk
SHARE+=			plain.files.mk
SHARE+=			latex.doc.mk
SHARE+=			latex.files.mk
SHARE+=			mpost.doc.mk
SHARE+=			mpost.files.mk

.include "generic.files.mk"

### End of file `Makefile'
