### Makefile -- Support for TeX and METAPOST

# Author: Michael Grünewald
# Date: Sam Jul  7 2007 18:12:07 CEST

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

FILES=			texmf.init.mk
FILES+=			texmf.uses.mk
FILES+=			texmf.module.mk
FILES+=			texmf.external.mk
FILES+=			texmf.depend.mk
FILES+=			texmf.clean.mk
FILES+=			texmf.build.mk
FILES+=			texmf.mpost.mk
FILES+=			texmf.draft.mk

FILES+=			tex.doc.mk
FILES+=			latex.doc.mk
FILES+=			mpost.doc.mk

OBSOLETE+=		tex.files.mk
OBSOLETE+=		tex.files.main.mk
OBSOLETE+=		latex.bibtex.mk

.include "project.mk"

### End of file `Makefile'
