### Makefile -- Mini project

# Author: Michael Grünewald
# Date: Sun Oct 13 10:50:45 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

SUBDIR+=	fibonacci
SUBDIR+=	newton
SUBDIR+=	golden_ratio

.include "bps.subdir.mk"

### End of file `Makefile'
