### Makefile -- Mini Basic

# Author: Michael Grünewald
# Date: Fri Oct 18 07:48:45 CEST 2013

# BSDMake Pallàs Scripts (http://home.gna.org/bsdmakepscripts/)
# This file is part of BSDMake Pallàs Scripts
#
# Copyright (C) 2013 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

PACK=	minibasic

SRCS =		main.ml
SRCS+=		basic_types.ml
SRCS+=		basic_parser.mly
SRCS+=		basic_lexer.mll

.include "ocaml.pack.mk"

### End of file `Makefile'
