### Makefile -- Newton's method

# Author: Michael Grünewald
# Date: Thu Oct  3 23:39:20 CEST 2013

# BSD Owl Scripts (https://bitbucket.org/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=	newton
SRCS+= 		newton.ml

USE_ODOC=	yes

ODOC_NAME=	newtontk
ODOC_TITLE=	Newton's method#'

.include "ocaml.lib.mk"

### End of file `Makefile'
