### Makefile -- Document with figures using LaTeX

# Author: Michael Grünewald
# Date: Sun Nov 23 17:58:17 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

DOCUMENT=		illustrated

SRCS=			illustrated.tex
SRCS+=			square.mp

.include "latex.doc.mk"

### End of file `Makefile'
