### Makefile -- Mini Basic

# Author: Michael Grünewald
# Date: Fri Oct  4 20:53:07 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

PROGRAM=	minibasic

SRCS =		main.ml
SRCS+=		basic_types.ml
SRCS+=		basic_parser.mly
SRCS+=		basic_lexer.mll

.include "ocaml.prog.mk"

### End of file `Makefile'
