### Makefile -- A simple static website

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

WWW=			index.html
WWWDIR=			${WWWROOTDIR}

SRCS+=			head-title.sgml
SRCS+=			page-title.sgml
SRCS+=			page-content.sgml
SRCS+=			more-ilink.sgml
SRCS+=			more-elink.sgml
SRCS+=			more-download.sgml
SRCS+=			head-css-local.sgml

.include "scroll.mk"

### End of file `Makefile'
