### Makefile -- A simple static website

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

WWW=			ocaml.html
WWWDIR=			${WWWROOTDIR}

SRCS+=			head-title.sgml
SRCS+=			page-title.sgml
SRCS+=			page-content.sgml
SRCS+=			more-ilink.sgml
SRCS+=			more-elink.sgml
SRCS+=			more-download.sgml

.include "scroll.mk"

### End of file `Makefile'
