### Makefile -- A simple static website

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

WWW+=			modern.css
WWW+=			modern_sz.css

WWW+=			classic.css
WWW+=			classic_sz.css

WWW+=			trendy.css

WWW+=			content.css
WWW+=			more.css
WWW+=			title.css
WWW+=			layout.css
WWW+=			scroll_layout.css

WWWDIR=			${WWWROOTDIR}/style

.include "www.files.mk"

### End of file `Makefile'
