### Makefile -- Mini Basic

# Author: Michael Grünewald
# Date: Fri Oct 18 07:48:45 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

PROG=		minibasic

SRCS=		basic_types.ml
SRCS+=		basic_parser.mly
SRCS+=		basic_lexer.mll
SRCS+=		minibasic.ml
SRCS+=		main.ml

.include "ocaml.prog.mk"

### End of file `Makefile'
