### Makefile -- Mini Basic

# Author: Michael Grünewald
# Date: Fri Oct 18 07:48:45 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

PROG=		minibasic

SRCS=		basic_types.ml
SRCS+=		basic_parser.mly
SRCS+=		basic_lexer.mll
SRCS+=		minibasic.ml
SRCS+=		main.ml

.include "ocaml.prog.mk"

### End of file `Makefile'
