.\" libfibonacci.3 -- Compute on fibonacci numbers
.\"
.\" Author: Michael Grünewald
.\" Date: Fri Nov  7 23:09:33 CET 2014
.\"
.\" BSD Owl Scripts (https://github.com/michipili/bsdowl)
.\" This file is part of BSD Owl Scripts
.\"
.\" Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
.\"
.\" This file must be used under the terms of the BSD license.
.\" This source file is licensed as described in the file LICENSE, which
.\" you should have received as part of this distribution.
.\"
.Dd November 14, 2014
.Dt LIBFIBONACCI 3
.Os
.Sh NAME
.Nm libfibonacci
.Nd Compute fibonacci numbers
.Sh LIBRARY
.Lb libfibonacci
.Sh SYNOPSIS
.In fibonacci.h
.Sh DESCRIPTION
The
.Lb libfibonacci
provides a function computing Fibonacci numbers.
.Sh SEE ALSO
The
.Em GNU multiple precision arithmetic library
is a starting point if you actually need to compute Fibonacci
numbers.
.Sh HISTORY
The
.Nm
library appeared as a demonstration library for bsdowl.
.Sh AUTHORS
.An -nosplit
This heat generating
.Nm
library was written by
.An Michael Gr\(:unewald Aq michipili@gmail.com .
