### Makefile -- Library for computing Fibonacci numbers

# Author: Michael Grünewald
# Date: Fri Nov 14 22:55:51 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

LIBRARY=		fibonacci

SRCS=			fibonacci.h
SRCS+=			fibonacci.c

.include "langc.lib.mk"

### End of file `Makefile'
