### Makefile -- A simple Python module

# Author: Michael Grünewald
# Date: Sat Nov 22 11:11:04 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		funniest
APIVERSION=		0
APIREVISION=		1
LIBVERSION=		${APIVERSION}.${APIREVISION}

USES+=			python:2.7
USES+=			setuptools

.include "python.lib.mk"

### End of file `Makefile'
