### Makefile -- A very simple program

# Author: Michael Grünewald
# Date: Sat Nov 15 16:10:58 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

PROGRAM=		goldenratio

SRCS=			goldenratio.c

.include "langc.prog.mk"

### End of file `Makefile'
