### Makefile -- Support files for noweb

# Author: Michael Grünewald
# Date: Sat Oct  3 19:09:28 CEST 2009

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

SHARE+=		nwlatex.css
FILES+=		nwlatex.tex

FILESDIR=	${datarootdir}/texmf-local/tex/latex${PACKAGEDIR}

.include "generic.files.mk"

### End of file `Makefile'
