### Makefile -- Support files for noweb

# Author: Michael Grünewald
# Date: Sat Oct  3 19:09:28 CEST 2009

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

SHARE+=		nwlatex.css
FILES+=		nwlatex.tex

FILESDIR=	${datarootdir}/texmf-local/tex/latex${PACKAGEDIR}

.include "generic.files.mk"

### End of file `Makefile'
