### Makefile -- Test noweb support with LaTeX

# Author: Michael Grünewald
# Date: Fri Nov 28 10:05:39 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

# IMPORTANT. This example is useful because it shows how to develop
# LaTeX packages with noweband bsdowl.  The LaTeX macros it produces
# are, however, not maintained. any more.

PACKAGE=		samhain
VERSION=		1.0
OFFICER=		michipili@gmail.com

SUBDIR=			class
SUBDIR+=		example
SUBDIR+=		manual

.include "generic.project.mk"

### End of file `Makefile'
