### Makefile

# Author: Michael Grünewald
# Date: Sat Jul  7 18:12:00 CEST 2007

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

SHARE+=			www.files.mk
SHARE+=			www.sgml.mk

.include "generic.files.mk"

### End of file `Makefile'
