### Makefile

# Author: Michaël Le Barbier Grünewald
# Date: Sam  7 jul 2007 18:12:00 CEST
# Lang: fr_FR.ISO8859-1

# $Id$


FILES = www.files.mk
FILES+= www.sgml.mk

.include "project.mk"

### End of file `Makefile'
