### Makefile -- Test OCaml bindings

# Author: Michael Grünewald
# Date: Fri Jan  9 11:03:59 CET 2015

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

TEST=	TestLibraryBindingStatic

.include "bsdowl.test.mk"

### End of file `Makefile'
