### Makefile -- Developement of applications with C

# Author: Michael Grünewald
# Date: Fri Nov  7 08:53:47 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

SHARE=			langc.init.mk
SHARE+=			langc.build.mk
SHARE+=			langc.uses.mk
SHARE+=			langc.module.mk
SHARE+=			langc.external.mk
SHARE+=			langc.depend.mk
SHARE+=			langc.prog.mk
SHARE+=			langc.lib.mk

.include "generic.files.mk"

### End of file `Makefile'
