### Makefile -- Developement of applications with C

# Author: Michael Grünewald
# Date: Fri Nov  7 08:53:47 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

FILES=			langc.init.mk
FILES+=			langc.build.mk
FILES+=			langc.uses.mk
FILES+=			langc.module.mk
FILES+=			langc.external.mk
FILES+=			langc.depend.mk
FILES+=			langc.prog.mk
FILES+=			langc.lib.mk

.include "project.mk"

### End of file `Makefile'
