### Makefile -- Developement of applications with C

# Author: Michael Grünewald
# Date: Fri Nov  7 08:53:47 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

SHARE=			langc.init.mk
SHARE+=			langc.build.mk
SHARE+=			langc.uses.mk
SHARE+=			langc.module.mk
SHARE+=			langc.external.mk
SHARE+=			langc.depend.mk
SHARE+=			langc.prog.mk
SHARE+=			langc.lib.mk

.include "generic.files.mk"

### End of file `Makefile'
