### Makefile -- Mini project

# Author: Michael Grünewald
# Date: Sun Oct 13 10:50:45 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

PACKAGE=	golden_ratio
VERSION=	1.0.0
OFFICER=	michipili@gmail.com

MODULE=		ocaml.lib:fibonacci
MODULE+=	ocaml.lib:newton
MODULE+=	ocaml.prog:golden_ratio
MODULE+=	ocaml.manual:manual

EXTERNAL=	ocaml.findlib:num

.include "generic.project.mk"

### End of file `Makefile'
