### Makefile -- Test Suite for scripts

# Author: Michael Grünewald
# Date: Fri Nov 21 21:54:07 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.


SUBDIR=		test_shell
SUBDIR+=	test_python

.include "generic.subdir.mk"

### End of file `Makefile'
