### Makefile -- Test Suite for scripts

# Author: Michael Grünewald
# Date: Fri Nov 21 21:54:07 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt


SUBDIR=		bsdmake
SUBDIR+=	ocaml
SUBDIR+=	langc
SUBDIR+=	langc++
SUBDIR+=	script
SUBDIR+=	config
SUBDIR+=	texmf

.include "generic.subdir.mk"

### End of file `Makefile'
