### Makefile -- Developement of applications with Objective Caml

# Author: Michael Grünewald
# Date: Sat Jul  7 18:12:48 CEST 2007

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

# The ocaml subsystem defines the following modules:
# - ocaml.prog -- Prepare OCaml programs
# - ocaml.lib -- Prepare OCaml libraries
# - ocaml.pack -- Prepare packed OCaml libraries
# - ocaml.meta -- Prepare OCaml findlib META files
# - ocaml.toplevel -- Prepare OCaml toplevels

FILES+= ocaml.uses.mk
FILES+= ocaml.module.mk
FILES+= ocaml.external.mk
FILES+= ocaml.build.mk
FILES+= ocaml.depend.mk
FILES+= ocaml.find.mk
FILES+= ocaml.meta.mk
FILES+= ocaml.init.mk
FILES+= ocaml.lex.mk
FILES+= ocaml.lib.mk
FILES+= ocaml.pack.mk
FILES+= ocaml.main.mk
FILES+= ocaml.object.mk
FILES+= ocaml.prog.mk
FILES+= ocaml.dirs.mk
FILES+= ocaml.source.mk
FILES+= ocaml.compile.mk
FILES+= ocaml.tools.mk
FILES+= ocaml.yacc.mk
FILES+= ocaml.odoc.mk
FILES+= ocaml.manual.mk
FILES+= ocaml.toplevel.mk

.include "project.mk"

### End of file `Makefile'
