### Makefile -- Developement of applications with Objective Caml

# Author: Michael Grünewald
# Date: Sat Jul  7 18:12:48 CEST 2007

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

# The ocaml subsystem defines the following modules:
# - ocaml.prog -- Prepare OCaml programs
# - ocaml.lib -- Prepare OCaml libraries
# - ocaml.pack -- Prepare packed OCaml libraries
# - ocaml.meta -- Prepare OCaml findlib META files
# - ocaml.toplevel -- Prepare OCaml toplevels

SHARE+=			ocaml.uses.mk
SHARE+=			ocaml.module.mk
SHARE+=			ocaml.external.mk
SHARE+=			ocaml.build.mk
SHARE+=			ocaml.depend.mk
SHARE+=			ocaml.find.mk
SHARE+=			ocaml.meta.mk
SHARE+=			ocaml.init.mk
SHARE+=			ocaml.lex.mk
SHARE+=			ocaml.lib.mk
SHARE+=			ocaml.pack.mk
SHARE+=			ocaml.main.mk
SHARE+=			ocaml.object.mk
SHARE+=			ocaml.prog.mk
SHARE+=			ocaml.dirs.mk
SHARE+=			ocaml.source.mk
SHARE+=			ocaml.compile.mk
SHARE+=			ocaml.tools.mk
SHARE+=			ocaml.yacc.mk
SHARE+=			ocaml.odoc.mk
SHARE+=			ocaml.manual.mk
SHARE+=			ocaml.toplevel.mk

.include "generic.files.mk"

### End of file `Makefile'
