### ocaml.lib.mk -- Building OCaml libraries

# Author: Michael Grünewald
# Date: Tue Apr  5 12:31:04 CEST 2005

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt


### SYNOPSIS

# LIBRARY=	newton
# SRCS+=	newton.ml
#
# .include "ocaml.lib.mk"


### DESCRIPTION

# Build an ocaml library, compiling each of the module listed in SRCS
# and creating a library named as LIBRARY.
#
# It supports building bytecode and native libraries, ocamlfind,
# lexers and parsers generated by ocamllex and ocamlyacc and
# debugging, profiling as well.

# Variables:
#
#
#  LIBRARY
#   The name of the library
#
#
#  SRCS
#   Files to put in the library
#
#   It can list implementation files, lexer and parser definitions.
#
#
#  LIBOWN, LIBGRP, LIBMODE, LIBNAME
#   Paramters of the library installation
#
#   See `bps.own.mk` for a closer description of these variables.
#
#
#  LIBDIR [${ocamllibdir}${PACKAGEDIR}]
#   The installation target for libraries
#
#   The value defined in `bps.own.mk` is suited for C libraries but not
#   for OCaml objects that are rather installed in the same location as
#   the standard library.
#
#
#  ocamllibdir [${libdir}]
#   Directory for ocaml libraries
#
#   See "USES+=site-lib" below.
#
#
# Uses:
#
#  site-lib: No argument allowed
#   Use ${libdir}/ocaml/site-lib as default value for ocamllibdir
#
#
#  dynlink: No argument allowed
#   Prepare dynlink plugins


### IMPLEMENTATION

THISMODULE=		ocaml.lib

.if !defined(LIBRARY)||empty(LIBRARY)
.error The ocaml.lib.mk expects you to set the LIBRARY variable to a sensible value.
.endif

PRODUCT=		${LIBRARY}
_PACKAGE_CANDIDATE=	${LIBRARY}

.include "ocaml.init.mk"

_OCAML_LIB:=		${LIBRARY}

.for lib in ${_OCAML_LIB}
SRCS.${lib:T}?=		${SRCS}
.if defined(_OCAML_COMPILE_NATIVE)
SRCS.${lib:T}.cmxa?=	${SRCS.${lib:T}}
_OCAML_SRCS+=		SRCS.${lib}.cmxa
_OCAML_CMXA+=		${lib:T}.cmxa
_OCAML_A+=		${lib:T}.a
_OCAML_SRCS.${lib:T}.cmxa+=\
			${SRCS.${lib}.cmxa:C@\.ml[ly]@.ml@:M*.ml:.ml=.cmx}
LIB+=			${lib}.cmxa ${lib}.a
.endif
.if defined(_OCAML_COMPILE_NATIVE)&&defined(_OCAML_COMPILE_PLUGIN)
_OCAML_CMXS+=		${SRCS.${lib}.cmxa:C@\.ml[ly]@.ml@:M*.ml:.ml=.cmxs}
.endif
.if defined(_OCAML_COMPILE_BYTE)
SRCS.${lib:T}.cma?=	${SRCS.${lib:T}}
_OCAML_SRCS+=		SRCS.${lib}.cma
_OCAML_CMA+=		${lib:T}.cma
_OCAML_SRCS.${lib:T}.cma+=\
			${SRCS.${lib:T}.cma:C@\.ml[ly]@.ml@:M*.ml:.ml=.cmo}
LIB+=			${lib}.cma
.endif
.if!empty(SRCS.${lib:T}:C@\.ml[ly]@.ml@:M*.ml)
LIB+=			${SRCS.${lib:T}:C@\.ml[ly]@.ml@:M*.ml:.ml=.cmi}
.endif
.endfor

.if !empty(_OCAML_CMXS)
LIB+=			${_OCAML_CMXS}
CLEANFILES+=		${_OCAML_CMXS}
.endif

.include "ocaml.main.mk"

.if !empty(_OCAML_CMXS)
.for plugin in ${_OCAML_CMXS}
${plugin}: ${plugin:.cmxs=.ml}
.endfor
.endif


.for lib in ${_OCAML_LIB}
.if defined(_OCAML_COMPILE_NATIVE)
${lib}.cmxa: ${_OCAML_SRCS.${lib}.cmxa}
.endif
.if defined(_OCAML_COMPILE_BYTE)
${lib}.cma: ${_OCAML_SRCS.${lib:T}.cma}
.endif
.endfor


.if exists(META)||exists(META.in)||defined(META)
.include "ocaml.meta.mk"
.endif

.include "bps.clean.mk"
.include "bps.files.mk"
.include "bps.usertarget.mk"

### End of file `ocaml.lib.mk'
