### Makefile -- Stubs for our rational arithmetic

# Author: Michael Grünewald
# Date: Fri Jan  9 11:34:36 CET 2015

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		rational_stubs

SRCS=			rational_stubs.c

DIRS=			${TESTSRCDIR}/librational
DIRS+=			/usr/local/lib/ocaml

.PATH: ${TESTSRCDIR}/librational

.include "langc.lib.mk"

### End of file `Makefile'
