### Makefile -- Install script programs and libraries

# Author: Michael Grünewald
# Date: Thu Nov 20 14:11:44 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

SHARE=			script.main.mk
SHARE+=			shell.prog.mk
SHARE+=			shell.lib.mk
SHARE+=			perl.prog.mk
SHARE+=			perl.uses.mk
SHARE+=			perl.init.mk
SHARE+=			perl.lib.mk
SHARE+=			python.prog.mk
SHARE+=			python.lib.mk
SHARE+=			python.init.mk
SHARE+=			python.uses.mk
SHARE+=			python.setuptools.mk

.include "generic.files.mk"

### End of file `Makefile'
