WWW = index.html
WWWDIR = ${WWWBASE}

INCLUDE = with.news
INCLUDE+= with.ilink
INCLUDE+= with.elink


SRCS = index.sgml
SRCS+= head-title.sgml
SRCS+= head-css.sgml
SRCS+= page-title.sgml
SRCS+= page-content.sgml
SRCS+= more-news.sgml
SRCS+= more-ilink.sgml
SRCS+= more-elink.sgml

.include "scroll.mk"
