### Makefile -- Custom toplevel

# Author: Michael Grünewald
# Date: Fri Oct  4 08:23:21 CEST 2013

# BSD Owl Scripts (https://bitbucket.org/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

TOPLEVEL=	toplevel
SRCS+= 		initialise_toplevel.ml

LIBS+=		unix
LIBS+=		str

.include "ocaml.toplevel.mk"

### End of file `Makefile'
