### Makefile -- Complex document using LaTeX

# Author: Michael Grünewald
# Date: Sun Nov 23 22:53:22 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

PAKCAGE=		complex
VERSION=		1.0
OFFICER=		michipili@gmail.com

SUBDIR=			chapter1
SUBDIR+=		chapter2
SUBDIR+=		main

.include "generic.project.mk"

### End of file `Makefile'
