### Makefile -- Complex document using LaTeX

# Author: Michael Grünewald
# Date: Sun Nov 23 22:53:22 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

PAKCAGE=		complex
VERSION=		1.0
OFFICER=		michipili@gmail.com

SUBDIR=			chapter1
SUBDIR+=		chapter2
SUBDIR+=		main

.include "generic.project.mk"

### End of file `Makefile'
