### Makefile -- Test misc.elisp.mk

# Author: Michaël Le Barbier Grünewald
# Date: Sam  7 jul 2007 18:08:19 CEST
# Lang: fr_FR.ISO8859-1

# $Id$


### SYNOPSIS

# $ make -I ../../make -I ../../misc install

SRCS+= emake1.el
SRCS+= emake2.el

ELISP_INSTALL_SRC.emake2.el = no

ELSIPDIR = ${.CURDIR:C%^${HOME}%%:H}/tmp/elisp
.include "misc.elisp.mk"

### End of file `Makefile'
