### Makefile -- Newton's method

# Author: Michael Grünewald
# Date: Sat Oct  5 20:40:24 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

LIBRARY=		fibonacci
SRCS+=			fibonacci.ml

.include "ocaml.lib.mk"

### End of file `Makefile'
