### Makefile -- A library to compute on rational numbers

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		rational

APIMAJOR=		1
APIMINOR=		0
APIPATCH=		0

LIBVERSION=		${APIMAJOR}.${APIMINOR}.${APIPATCH}

SRCS=			rational.hpp
SRCS+=			rational_operation.cpp
SRCS+=			rational_print.cpp

MAN=			librational.3

.include "langc++.lib.mk"

### End of file `Makefile'
