### Makefile -- Collection de Makefiles `make'

# Author: Michaël Grünewald
# Date: Ven 10 fév 2006 16:51:08 GMT
# Lang: fr_FR.ISO8859-1

# $Id$


FILES+=	make.init.mk
FILES+=	make.own.mk
FILES+= make.usertarget.mk
FILES+=	make.clean.mk
FILES+=	make.subdir.mk
FILES+=	make.files.mk

.include "project.mk"

### End of file `Makefile'
