.\" showconfig.1 -- Show self-configuration
.\"
.\" BSD Owl Scripts (https://github.com/michipili/bsdowl)
.\" This file is part of BSD Owl Scripts
.\"
.\" Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
.\"
.\" This file must be used under the terms of the BSD license.
.\" This source file is licensed as described in the file LICENSE, which
.\" you should have received as part of this distribution.
.\"
.Dd November 21, 2014
.Dt SHOWCONFIG 1
.Os
.Sh NAME
.Nm showconfig
.Nd Show self-configuration
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
program prints its configuration, that is, the directory variables it
uses and their values.
.Sh SEE ALSO
The
.Em GNU coding standards, last updated September 13, 2013.
.Sh HISTORY
The
.Nm
program appeared as a demonstration shell script for bsdowl.
.Sh AUTHORS
.An -nosplit
This heat generating
.Nm
library was written by
.An Michael Gr\(:unewald Aq michipili@gmail.com .
