### bps.m4.mk -- Support the M4 macro preprocessor

# Author: Michael Grünewald
# Date: Sun Nov 23 09:50:13 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

# Variables:
#
#  _M4_CANDIDATE [not set]
#   The list of files potentially generated by m4
#
#
#  M4FLAGS [not set]
#   Flags for the M4 command
#
#
#  M4MACROS [not set]
#   List of macro files to always include

.if !target(__<bps.init.mk>__)
.error bps.m4.mk cannot be included directly.
.endif

.if !target(__<bps.m4.mk>__)
__<bps.m4.mk>__:

_M4_TOOL=		${M4}
.for var in M4FLAGS M4MACROS
.if defined(${var})&&!empty(${var})
_M4_TOOL+=		${${var}}
.endif
.endfor

.if defined(_M4_CANDIDATE)
.for file in ${_M4_CANDIDATE}
.if exists(${file}.m4)
${file}: ${file}.m4
	${_M4_TOOL} ${.ALLSRC} > ${.TARGET} || (${RM} ${.TARGET}; exit 1)
CLEANFILES+=		${file}
.endif
.endfor
.endif

.endif # !target(__<bps.m4.mk>__)

### End of file `bps.m4.mk'
