### Makefile -- Core facilities

# Author: Michael Grünewald
# Date: Fri 10 Feb 2006 16:51:08 GMT

# BSD Owl Scripts (https://bitbucket.org/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

FILES+=	bps.init.mk
FILES+= bps.credentials.mk
FILES+= bps.objdir.mk
FILES+=	bps.own.mk
FILES+= bps.man.mk
FILES+= bps.usertarget.mk
FILES+=	bps.clean.mk
FILES+=	bps.subdir.mk
FILES+=	bps.files.mk
FILES+= bps.autoconf.mk
FILES+= bps.project.mk

.include "project.mk"

### End of file `Makefile'
