### Makefile -- Core facilities

# Author: Michael Grünewald
# Date: Fri Feb 10 16:51:08 GMT 2006

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

SHARE=			bps.init.mk
SHARE+=			bps.bpsconfig.mk
SHARE+=			bps.package.mk
SHARE+=			bps.uses.mk
SHARE+=			bps.module.mk
SHARE+=			bps.external.mk
SHARE+=			bps.product.mk
SHARE+=			bps.architecture.mk
SHARE+=			bps.configuration.mk
SHARE+=			bps.credentials.mk
SHARE+=			bps.objdir.mk
SHARE+=			bps.own.mk
SHARE+=			bps.man.mk
SHARE+=			bps.usertarget.mk
SHARE+=			bps.clean.mk
SHARE+=			bps.subdir.mk
SHARE+=			bps.files.mk
SHARE+=			bps.autoconf.mk
SHARE+=			bps.preparatives.mk
SHARE+=			bps.replace.mk
SHARE+=			bps.project.mk
SHARE+=			bps.m4.mk
SHARE+=			bps.noweb.mk
SHARE+=			bps.test-expected.mk

.include "generic.files.mk"

### End of file `Makefile'
