### Makefile -- Collection de Makefiles `make'

# Author: Michaël Le Barbier Grünewald
# Date: Ven 10 fév 2006 16:51:08 GMT
# Lang: fr_FR.ISO8859-1

# $Id$

FILES+=	bps.init.mk
FILES+= bps.credentials.mk
FILES+= bps.objdir.mk
FILES+=	bps.own.mk
FILES+= bps.usertarget.mk
FILES+=	bps.clean.mk
FILES+=	bps.subdir.mk
FILES+=	bps.files.mk
FILES+= bps.autoconf.mk
FILES+= bps.project.mk
FILES+= bps.config.mk

REALCLEANFILES+= bps.config.mk

.include "project.mk"

### End of file `Makefile'
