### Makefile -- Preparation of the golden_ratio manual

# Author: Michael Grünewald
# Date: Tue Oct 15 21:37:11 CEST 2013

# Copyright (c) 2013 Michael Grünewald
# All rights reserved.
#
# This file is part of Waermondt.


ODOC_TITLE= Golden Ratio

DIRS+= ../newton
MANUAL+= newton.odoc

DIRS+= ../fibonacci
MANUAL+= fibonacci.odoc

.include "ocaml.manual.mk"

### End of file `Makefile'
