# Cookie: SYNOPSIS TARGET VARIABLE EN DOCUMENTATION
PREFIX = ${HOME}

SUBDIR = index
SUBDIR+= tex
SUBDIR+= ocaml
SUBDIR+= writing
SUBDIR+= generation
SUBDIR+= guidelines
SUBDIR+= style

.include "website.mk"
