### Makefile -- Computing the golden ratio

# Author: Michael Grünewald
# Date: Sat Oct  5 20:47:48 CEST 2013

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2017 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.

PROGRAM=	golden_ratio

SRCS=		main.ml

.include "ocaml.prog.mk"

### End of file `Makefile'
