### Makefile -- Test for Perl programs, modules and extensions

# Author: Michael Grünewald
# Date: Fri Nov 21 15:28:45 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2002–2016 Michael Grünewald. All Rights Reserved.
#
# This file must be used under the terms of the BSD license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.


### SYNOPSIS

### DESCRIPTION

.if !target(__<Makefile>__)
__<Makefile>__:

.endif # !target(__<Makefile>__)

### End of file `Makefile'
