### Makefile -- Test for Perl programs, modules and extensions

# Author: Michael Grünewald
# Date: Fri Nov 21 15:28:45 CET 2014

# BSD Owl Scripts (https://github.com/michipili/bsdowl)
# This file is part of BSD Owl Scripts
#
# Copyright © 2005–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt


### SYNOPSIS

### DESCRIPTION

.if !target(__<Makefile>__)
__<Makefile>__:

.endif # !target(__<Makefile>__)

### End of file `Makefile'
