.\" hello_world.1 -- Count bytes, words and lines in a file
.\"
.\" Author: Michael Grünewald
.\" Date: Fri Nov  7 10:26:54 CET 2014
.\"
.\" BSD Owl Scripts (https://github.com/michipili/bsdowl)
.\" This file is part of BSD Owl Scripts
.\"
.\" Copyright © 2005–2014 Michael Grünewald
.\"
.\" This file must be used under the terms of the CeCILL-B.
.\" This source file is licensed as described in the file COPYING, which
.\" you should have received as part of this distribution. The terms
.\" are also available at
.\" http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt
.\"
.Dd November 7, 2014
.Dt HELLO_WORLD 1
.Os
.Sh NAME
.Nm hello_world
.Nd send a greeting to the world
.Sh SYNOPSIS
.Nm hello_world
.Sh DESCRIPTION
The
.Nm
utility displays a cheerful greeting.
.Sh HISTORY
The
.Nm
command appeared as a demonstration program for bsdowl, it is inspired
by a famous example by Kernighan and Ritchie.
.Sh AUTHORS
.An -nosplit
This simplistic
.Nm
program was written by
.An Michael Gr\(:unewald Aq michipili@gmail.com .
